[package]
name = "decursion"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
bumpalo = { version = "3.16.0", features = ["boxed", "collections"] }
futures = "0.3.30"
futures-lite = "2.3.0"
scoped-tls-hkt = "0.1.5"
